$AzureUserName="AzureUserNameValue"
$AzurePassword="AzurePasswordValue"
$AzureTenantID="AzureTenantIDValue"
$AzureSubscriptionID="AzureSubscriptionIDValue"
$DeploymentID="DeploymentIDValue"
$AdminPassword= "AdminPasswordValue"
